# -*- coding: utf-8 -*-
"""MYPROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hB789sl5vqpLg3d2YYhXXA9XL-FbYkf6
"""

#!pip install git+https://www.github.com/keras-team/keras-contrib.git

#!pip install --upgrade keras

from keras.layers import (
    Input, Dense, Reshape, Flatten, Dropout, Concatenate,
    BatchNormalization, Activation, ZeroPadding2D
)
from keras.layers import LeakyReLU, PReLU
from keras.layers import UpSampling2D, Conv2D, Conv2DTranspose
from keras.layers import Conv2DTranspose
from keras.models import Model

#!pip install --upgrade tensorflow
#!pip install tensorflow==2.15

import tensorflow
from tensorflow.keras.optimizers import Adam

from google.colab import drive
drive.mount('/content/drive')

#!unzip "/content/drive/My Drive/V-20211025T114121Z-001.zip" -d "/content/drive/My Drive/"

import cv2
from glob import glob
import numpy as np
import matplotlib.pyplot as plt

dataset_name ='V'

from google.colab import drive
drive.mount('/content/drive')

!mogrify -format png '/content/drive/My Drive/c/JPG/*jpg'

!mkdir datasets
!wget - N $URL
!tar -zxvf $TAR_FILE -C ./datasets/
!rm $TAR_FILE
!mkdir saved_models

#keras.optimizers.Adam(lr=0.0002, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
import tensorflow as tf
optimizer = tf.keras.optimizers.legacy.Adam(lr=0.0002, beta_1=0.5)

from tensorflow.keras.optimizers import(Adam, RMSprop)

from keras.layers import( Conv2D, UpSampling2D)

from keras.models import Model

img_row=256
img_col = 256
channels =3
img_shape=(img_row,img_col,channels)
patch= int(img_row/2**4)
disc_patch=(patch,patch,1)
dwf=64
upf =64
img_A= Input(shape=(256,256,3))
img_B =Input(shape=(256,256,3))

def encode(inputs,filters,kernel=4,bn=True):
  d=Conv2D(filters=filters,kernel_size=kernel,strides=2,padding='same')(inputs)
  d=LeakyReLU(alpha=0.2)(d)
  if bn:
    d= BatchNormalization(momentum=0.8)(d)

  return d

def decode(layer_input, skip_input, filters, f_size=4, dropout_rate=0):
            """Layers used during upsampling"""
            u = UpSampling2D(size=2)(layer_input)
            #u = Conv2D(filters, kernel_size=f_size, strides=1, padding='same', activation='relu')(u)
            u = Conv2DTranspose(filters, kernel_size=f_size, strides=1, padding='same', activation='relu')(u)
            if dropout_rate:
                u = Dropout(dropout_rate)(u)
            u = BatchNormalization(momentum=0.8)(u)
            u = Concatenate()([u, skip_input])
            return u

"""**Generator Architecture**"""

def generator():
  inputs=Input(shape=(256,256,3))
  d0=encode(inputs,dwf,bn=False)
  d1=encode(d0,dwf*2)
  d2=encode(d1,dwf*4)
  d3=encode(d2,dwf*8)
  d4=encode(d3,dwf*8)
  d5=encode(d4,dwf*8)
  d6=encode(d5,dwf*8)
  ## upsampling##
  u1=decode(d6,d5,upf)
  u2=decode(u1,d4,upf*8)
  u3=decode(u2,d3,upf*8)
  u4=decode(u3,d2,upf*8)
  u5=decode(u4,d1,upf*4)
  u6=decode(u5,d0,upf*2)
  u7=UpSampling2D(size=2)(u6)
  out = Conv2D(channels,kernel_size=4,strides=1,padding='same',activation='tanh' )(u7)
  return Model(inputs,out)

G=generator()

G.summary()
# Input images and their conditioning images
img_A = Input(shape=img_shape)
img_B = Input(shape=img_shape)

from google.colab import drive
drive.mount('/content/drive')

# Path to the directory containing your images on Google Drive
filename = '/content/drive/MyDrive/Colab Notebooks/New/generator.png'
tf.keras.utils.plot_model(G, to_file=filename, show_shapes=True)

"""**Discriminator Architecture**"""

def descriminator():
  combined_imgs = Concatenate(axis=-1)([img_A, img_B])
  d1=encode(combined_imgs,dwf,bn=False)
  d2=encode(d1,dwf*2)
  d3=encode(d2,dwf*4)
  d4=encode(d3,dwf*8)
  validity = Conv2D(1, kernel_size=4, strides=1, padding='same')(d4)
  return Model([img_A, img_B], validity)

D=descriminator()
D.summary()

from google.colab import drive
drive.mount('/content/drive')

# Path to the directory containing your images on Google Drive
filename = '/content/drive/MyDrive/Colab Notebooks/New/discriminator.png'
tf.keras.utils.plot_model(D, to_file=filename, show_shapes=True)

"""**Finding loss and accuracy**"""

D.compile(loss='mse',
            optimizer=optimizer,
            metrics=['accuracy'])
# By conditioning on B generate a fake version of A
fake_A = G(img_B)
 # Discriminators determines validity of  condition pairs
valid = D([fake_A, img_B])

#combined model LAmbda =100
combined = Model(inputs=[img_A, img_B], outputs=[valid, fake_A])
combined.compile(loss=['mse', 'mae'],
                              loss_weights=[1, 100],
                              optimizer=optimizer)

#print(fake_A.shape)
# For the combined model we will only train the generator
D.trainable = False
n_batches= 1;

#image resolution for resizing
img_res=(256,256)
def imread( path):
        cv2.imread(path)

!mkdir "./saved_model"

##load datasets

def load_data( batch_size=1, is_testing=False):
        data_type = "train" if not is_testing else "test"
        path = glob('/content/drive/My Drive/%s/%s/*' % (dataset_name, data_type))

        batch_images = np.random.choice(path, size=batch_size)

        imgs_A = []
        imgs_B = []
        for img_path in batch_images:
            img = cv2.imread(img_path)

            h, w, _ = img.shape
            _w = int(w/2)
            img_A, img_B = img[:, :_w, :], img[:, _w:, :]

            img_A = cv2.resize(img_A, img_res)
            img_B = cv2.resize(img_B, img_res)

            # If training => do random flip
            if not is_testing and np.random.random() < 0.5:
                img_A = np.fliplr(img_A)
                img_B = np.fliplr(img_B)

            imgs_A.append(img_A)
            imgs_B.append(img_B)

        imgs_A = np.array(imgs_A)/127.5 - 1.
        imgs_B = np.array(imgs_B)/127.5 - 1.

        return imgs_A, imgs_B

#load batch
def load_batch(batch_size=1, is_testing=False):
        data_type = "train" if not is_testing else "val"
        path = glob('/content/drive/My Drive/%s/%s/*' % (dataset_name, data_type))

        n_batches = int(len(path) / batch_size)

        for i in range(n_batches-1):
            batch = path[i*batch_size:(i+1)*batch_size]
            imgs_A, imgs_B = [], []
            for img in batch:
                img = cv2.imread(img)
                h, w, _ = img.shape
                half_w = int(w/2)
                img_A = img[:, :half_w, :]
                img_B = img[:, half_w:, :]

                img_A = cv2.resize(img_A, img_res)
                img_B = cv2.resize(img_B, img_res)

                if not is_testing and np.random.random() > 0.5:
                        img_A = np.fliplr(img_A)
                        img_B = np.fliplr(img_B)

                imgs_A.append(img_A)
                imgs_B.append(img_B)

            imgs_A = np.array(imgs_A)/127.5 - 1.
            imgs_B = np.array(imgs_B)/127.5 - 1.

            yield imgs_A, imgs_B

def sample_images(epoch, batch_i):

        r, c = 3, 3

        imgs_A, imgs_B = load_data(batch_size=3, is_testing=True)
        fake_A = G.predict(imgs_B)

        gen_imgs = np.concatenate([imgs_B, fake_A, imgs_A])

        # Rescale images 0 - 1
        gen_imgs = 0.5 * gen_imgs + 0.5

        titles = ['Sketch', 'Generated', 'Original']
        fig, axs = plt.subplots(r, c)
        cnt = 0
        for i in range(r):
            for j in range(c):
                axs[i,j].imshow(gen_imgs[cnt])
                axs[i, j].set_title(titles[i])
                axs[i,j].axis('off')
                cnt += 1
        plt.show()
        plt.close()

"""**Training**"""

import datetime
import os
import numpy as np
import matplotlib.pyplot as plt
from keras.applications.inception_v3 import InceptionV3, preprocess_input
from keras.models import Model
from scipy.linalg import sqrtm
from keras.preprocessing import image


def train(epochs, batch_size=1, sample_interval=50):
    start_time = datetime.datetime.now()
    # Adversarial loss ground truths
    valid = np.ones((batch_size,) + disc_patch)
    fake = np.zeros((batch_size,) + disc_patch)
    print(valid.shape)

    # Lists to store loss values
    d_loss_list = []
    g_loss_list = []
    d_acc_list = []
    g_acc_list = []
    for epoch in range(epochs):
        for batch_i, (imgs_A, imgs_B) in enumerate(load_batch(batch_size)):

            # ---------------------
            #  Train Discriminator
            # ---------------------

            # Condition on B and generate a translated version
            fake_A = G.predict(imgs_B)

            # Train the discriminators (original images = real / generated = Fake)
            d_loss_real = D.train_on_batch([imgs_A, imgs_B], valid)
            d_loss_fake = D.train_on_batch([fake_A, imgs_B], fake)
            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

            # Append the loss values to the lists
            d_loss_list.append(d_loss[0])
            d_acc_list.append(100 * d_loss[1])  # Append discriminator accuracy

            # -----------------
            #  Train Generator
            # -----------------

            # Train the generators
            g_loss = combined.train_on_batch([imgs_A, imgs_B], [valid, imgs_A])
            # Append the loss values to the lists
            g_loss_list.append(g_loss[0])
            g_acc_list.append(100 * g_loss[1])
            elapsed_time = datetime.datetime.now() - start_time
            # Plot the progress
            print("[Epoch %d/%d] [Batch %d] [D loss: %f, acc: %3d%%] [G loss: %f] time: %s" % (
                epoch, epochs, batch_i, d_loss[0], 100*d_loss[1], g_loss[0], elapsed_time))

            # Append the loss values to the lists
            d_loss_list.append(d_loss[0])
            g_loss_list.append(g_loss[0])

            # If at save interval => save generated image samples
            if batch_i % sample_interval == 0:
                sample_images(epoch, batch_i)
                gen_weights_path = os.path.join('./saved_model/gen_weights_epoch_%s.h5' % (epoch))
                G.save_weights(gen_weights_path, overwrite=True)
             # Calculate FID at sample intervals

# Plotting the training history
    plt.figure(figsize=(12, 6))
    plt.plot(d_loss_list, label='Discriminator Loss')
    plt.plot(g_loss_list, label='Generator Loss')
    plt.xlabel('Batch Iterations')
    plt.ylabel('Loss')
    plt.legend()
    plt.title('Discriminator and Generator Loss Over Time')
    plt.show()

    plt.figure(figsize=(12, 6))
    plt.plot(d_acc_list, label='Discriminator Accuracy')  # Plot discriminator accuracy
    plt.plot(g_acc_list, label='Generator Accuracy')  # Plot Generator accuracy
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title('Discriminator and Generator Accuracy Over Time')
    plt.show()

train(100,32,100)

import datetime
import os
import numpy as np
import matplotlib.pyplot as plt
from keras.applications.inception_v3 import InceptionV3, preprocess_input
from keras.models import Model
from scipy.linalg import sqrtm
from keras.preprocessing import image
from sklearn.model_selection import KFold
from keras.optimizers import Adam

# Assuming these are defined elsewhere in your code
# load_batch = ...
# combined = ...
# sample_images = ...
# G = ...
# D = ...
# disc_patch = ...

# Set the number of folds
num_folds = 10
kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)

# Initialize variables to accumulate metrics
total_tp_real, total_fp_real, total_fn_real, total_tn_real = 0, 0, 0, 0
total_tp_fake, total_fp_fake, total_fn_fake, total_tn_fake = 0, 0, 0, 0
total_accuracy_real, total_recall_real, total_precision_real = 0, 0, 0
total_accuracy_fake, total_recall_fake, total_precision_fake = 0, 0, 0

# Define a function to calculate precision, recall, and accuracy
def calculate_metrics(y_true, y_pred):
    true_positives = np.sum(np.round(y_pred) * y_true)
    false_positives = np.sum(np.round(y_pred) * (1 - y_true))
    false_negatives = np.sum((1 - np.round(y_pred)) * y_true)

    # Corrected total_samples calculation
    total_samples = len(y_true)

    true_negatives = total_samples - (true_positives + false_positives + false_negatives)
    true_negatives = max(0, true_negatives)  # Ensure true_negatives is non-negative

    accuracy = (true_positives + true_negatives) / total_samples if total_samples > 0 else 0.0
    accuracy = max(0.0, min(accuracy, 1.0))  # Ensure accuracy is within [0, 1]

    recall = true_positives / (true_positives + false_negatives + 1e-9)
    precision = true_positives / (true_positives + false_positives + 1e-9)

    recall = max(0.0, min(recall, 1.0))  # Ensure recall is within [0, 1]
    precision = max(0.0, min(precision, 1.0))  # Ensure precision is within [0, 1]

    return true_positives, false_positives, false_negatives, true_negatives, accuracy, recall, precision


# Define custom learning rates
discriminator_lr = 0.0002
generator_lr = 0.0002

# Compile models with custom learning rates
D.compile(optimizer=Adam(learning_rate=discriminator_lr), loss='binary_crossentropy', metrics=['accuracy'])
combined.compile(optimizer=Adam(learning_rate=generator_lr), loss=['binary_crossentropy', 'mae'], loss_weights=[1, 100])

def train(epochs, batch_size=1, sample_interval=50):
    global total_tp_real, total_fp_real, total_fn_real, total_tn_real
    global total_tp_fake, total_fp_fake, total_fn_fake, total_tn_fake
    global total_accuracy_real, total_recall_real, total_precision_real
    global total_accuracy_fake, total_recall_fake, total_precision_fake

    start_time = datetime.datetime.now()
    valid = np.ones((batch_size,) + disc_patch)
    fake = np.zeros((batch_size,) + disc_patch)

    d_loss_list = []
    g_loss_list = []
    d_acc_list = []

    for epoch in range(epochs):
        for batch_i, (imgs_A, imgs_B) in enumerate(load_batch(batch_size)):
            fake_A = G.predict(imgs_B)
            binary_labels = np.ones_like(valid)

            # Train the discriminators (original images = real / generated = Fake)
            d_loss_real = D.train_on_batch([imgs_A, imgs_B], binary_labels)
            d_loss_fake = D.train_on_batch([fake_A, imgs_B], fake)

            # Calculate metrics for the real data
            tp_real, fp_real, fn_real, tn_real, accuracy_real, recall_real, precision_real = calculate_metrics(binary_labels, d_loss_real)

            # Update total metrics for real data
            total_tp_real += tp_real
            total_fp_real += fp_real
            total_fn_real += fn_real
            total_tn_real += tn_real
            total_accuracy_real += accuracy_real
            total_recall_real += recall_real
            total_precision_real += precision_real

            binary_labels_fake = np.zeros_like(fake)

            # Calculate metrics for the generated data
            tp_fake, fp_fake, fn_fake, tn_fake, accuracy_fake, recall_fake, precision_fake = calculate_metrics(binary_labels_fake, d_loss_fake)

            # Update total metrics for generated data
            total_tp_fake += tp_fake
            total_fp_fake += fp_fake
            total_fn_fake += fn_fake
            total_tn_fake += tn_fake
            total_accuracy_fake += accuracy_fake
            total_recall_fake += recall_fake
            total_precision_fake += precision_fake

            d_loss_list.append(d_loss_real[0])
            d_acc_list.append(100 * d_loss_real[1])

            # Train the generators
            g_loss = combined.train_on_batch([imgs_A, imgs_B], [valid, imgs_A])
            g_loss_list.append(g_loss[0])

            elapsed_time = datetime.datetime.now() - start_time
            print("[Epoch %d/%d] [Batch %d] [D loss: %f, acc: %3d%%] [G loss: %f] time: %s" % (
                epoch, epochs, batch_i, d_loss_real[0], 100 * d_loss_real[1], g_loss[0], elapsed_time))

            if batch_i % sample_interval == 0:
                sample_images(epoch, batch_i)
                gen_weights_path = os.path.join('./saved_model/gen_weights_epoch_%s.h5' % (epoch))
                G.save_weights(gen_weights_path, overwrite=True)

        # Calculate average metrics for each epoch
        avg_accuracy_real = total_accuracy_real / (batch_i + 1)
        avg_recall_real = total_recall_real / (batch_i + 1)
        avg_precision_real = total_precision_real / (batch_i + 1)

        avg_accuracy_fake = total_accuracy_fake / (batch_i + 1)
        avg_recall_fake = total_recall_fake / (batch_i + 1)
        avg_precision_fake = total_precision_fake / (batch_i + 1)

        print("[Epoch %d/%d] [D loss: %f, acc: %3d%%] [G loss: %f]" % (
            epoch, epochs, d_loss_real[0], 100 * d_loss_real[1], g_loss[0]))
        print("Real Data Metrics: TP=%d, FP=%d, FN=%d, TN=%d, Accuracy=%.4f, Recall=%.4f, Precision=%.4f" % (
            total_tp_real, total_fp_real, total_fn_real, total_tn_real,
            avg_accuracy_real, avg_recall_real, avg_precision_real))
        print("Generated Data Metrics: TP=%d, FP=%d, FN=%d, TN=%d, Accuracy=%.4f, Recall=%.4f, Precision=%.4f" % (
            total_tp_fake, total_fp_fake, total_fn_fake, total_tn_fake,
            avg_accuracy_fake, avg_recall_fake, avg_precision_fake))

        total_tp_real, total_fp_real, total_fn_real, total_tn_real = 0, 0, 0, 0
        total_tp_fake, total_fp_fake, total_fn_fake, total_tn_fake = 0, 0, 0, 0
        total_accuracy_real, total_recall_real, total_precision_real = 0, 0, 0
        total_accuracy_fake, total_recall_fake, total_precision_fake = 0, 0, 0

    plt.figure(figsize=(12, 6))
    plt.plot(d_loss_list, label='Discriminator Loss')
    plt.plot(g_loss_list, label='Generator Loss')
    plt.plot(d_acc_list, label='Discriminator Accuracy')
    plt.xlabel('Batch Iterations')
    plt.ylabel('Loss/Accuracy')
    plt.legend()
    plt.title('Discriminator and Generator Loss/Accuracy Over Time')
    plt.show()

# Call the train function with the desired parameters
train(epochs=100, batch_size=32, sample_interval=100)

!nvidia-smi

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
def build_cnn_model(input_shape):
    model = Sequential()

    model.add(Conv2D(32, (3, 3), input_shape=input_shape, activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    return model

# Build and compile the CNN model
cnn_model = build_cnn_model(img_shape)
cnn_model.summary()

# Training loop
def train(epochs, batch_size=1, sample_interval=50):
    start_time = datetime.datetime.now()
    # Adversarial loss ground truths
    valid = np.ones((batch_size,) + disc_patch)
    fake = np.zeros((batch_size,) + disc_patch)
    print(valid.shape)

    # Lists to store loss values
    d_loss_list = []
    g_loss_list = []
    d_acc_list = []

    for epoch in range(epochs):
        for batch_i, (imgs_A, imgs_B) in enumerate(load_batch(batch_size)):

            # ... (Your existing code)

            # Train the CNN model for person identification
            cnn_loss = cnn_model.train_on_batch(imgs_A, np.ones((batch_size, 1)))  # Assuming imgs_A contains person images
            print(f"CNN Loss: {cnn_loss}")

def generate_output(generator_model, input_data):
    # Assuming generator_model is the trained GAN generator model
    generated_images = generator_model.predict(input_data)

    # Post-process or visualize the generated_images as needed

    return generated_images

# Load the trained generator model weights
generator_model = generator()
generator_model.load_weights('./saved_model/gen_weights_epoch_10.h5')  # Change the path accordingly

# Assuming input_data is a batch of input images
input_data = load_data(batch_size=1, is_testing=True)[0]

# Generate output using the trained generator
output_images = generate_output(generator_model, input_data)

# Visualize the input and generated output
for i in range(len(input_data)):
    plt.figure(figsize=(8, 4))
    plt.subplot(1, 2, 2)
    plt.imshow(0.5 * output_images[i] + 0.5)  # Rescale generated output
    plt.title('Generated Image')

    plt.subplot(1, 2, 1)
    plt.imshow(0.5 * input_data[i] + 0.5)  # Rescale input_data
    plt.title('Person Image')

    plt.show()

